fullnameOverride: vault-unsealer

apiServer: https://kubernetes.default.svc

image:
  repository: ghcr.io/dmahmalat/vault-unsealer
  tag: 0.0.9
  pullPolicy: IfNotPresent

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule