fullnameOverride: vault

injector:
  enabled: false

server:
  dataStorage:
    size: 1Gi
  extraSecretEnvironmentVars:
  - envName: VAULT_CACERT
    secretName: cockroachdb-client-secret
    secretKey: ca.crt
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "cockroachdb" {
        connection_url = "postgres://Larry:potate@cockroachdb-public.core-services.svc.cluster.local:26257/vault?sslmode=verify-full"
        ha_enabled     = "true"
      }
      service_registration "kubernetes" {}
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule