mode: "distributed"

fullnameOverride: minio

extraEnvVars:
  - name: MINIO_SERVER_URL
    value: https://s3.dev.skyloft.cc/
  - name: MINIO_BROWSER_REDIRECT_URL
    value: https://s3.dev.skyloft.cc/dashboard/
  - name: MINIO_ROOT_USER
    valueFrom:
      secretKeyRef:
        name: minio-access-key
        key: AWS_ACCESS_KEY_ID
  - name: MINIO_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: minio-access-key
        key: AWS_SECRET_ACCESS_KEY

persistence:
  size: 2Gi

tls:
  existingSecret: cert-dev.skyloft.cc

defaultBuckets: "skyloft"

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule