fullnameOverride: minio

mode: distributed
replicas: 4
drivesPerNode: 1
pools: 1

persistence:
  size: 2Gi

environment:
- name: MINIO_SERVER_URL
  value: https://s3.dev.skyloft.cc/
- name: MINIO_BROWSER_REDIRECT_URL
  value: https://s3.dev.skyloft.cc/dashboard/
- name: MINIO_ROOT_USER
  valueFrom:
    secretKeyRef:
      name: minio-access-key
      key: AWS_ACCESS_KEY_ID
- name: MINIO_ROOT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: minio-access-key
      key: AWS_SECRET_ACCESS_KEY

tls:
  enabled: false #TEST

users:
- accessKey: testing #TEST
  existingSecret: minio-access-key
  existingSecretKey: AWS_SECRET_ACCESS_KEY
  policy: readwrite

buckets:
- name: backup
  policy: none
  purge: false
  versioning: false
  objectlocking: false

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule