configs:
  params:
    "server.insecure": true

controller:
  replicas: 2

server:
  replicas: 2
  autoscaling:
    minReplicas: 2

repoServer:
  replicas: 2
  autoscaling:
    minReplicas: 2

applicationSet:
  replicaCount: 2
  extraEnv:
  - name: "ARGOCD_SYNC_WAVE_DELAY"
    value: 60

configs:
  cm:
    "timeout.reconciliation": 60s

global:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule