apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyloft-dev
  namespace: core-services
spec:
  project: core-services
  sources:
  - repoURL: ghcr.io/dmahmalat/charts
    targetRevision: 0.0.7
    chart: skyloft
    helm:
      parameters:
      - name: landscape
        value: dev
      - name: dnsUpdate.domain
        value: dev-master.skyloft.cc
      - name: dnsUpdate.secret
        value: master-dns-update
      - name: dnsUpdate.image
        value: ghcr.io/dmahmalat/wget
      - name: dnsUpdate.cron
        value: "* * * * *"
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true