apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyloft-dev
  namespace: core-services
spec:
  project: core-services
  sources:
  - repoURL: https://dmahmalat.github.io/charts
    targetRevision: v1.0.0
    chart: skyloft
    helm:
      parameters:
      - name: landscape
        value: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true