apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  namespace: core-services
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Core Services Applications Resources
  sourceRepos:
  - '*'
  destinations:
  - namespace: core-services
    server: https://kubernetes.default.svc
    name: in-cluster
  orphanedResources:
    warn: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyloft-dev
  namespace: core-services
spec:
  project: core-services
  source:
    repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    path: dev/core-services
    directory:
      recurse: false
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true