apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyloft-dev
  namespace: core-services
spec:
  project: default
  source:
    repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    path: dev
    directory:
      recurse: false
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true