ingress:
  enabled: true
  host: s3.dev.skyloft.cc
  cert: cert-dev.skyloft.cc

backup:
  cron: "45 * * * *"
  src:
    bucket: skyloft
    region: skyloft
  dst:
    bucket: skyloft-storage-backup-dev

secrets:
  minio: minio-access-key
  gcs: gcs-access-key

image: docker.io/rclone/rclone:1.62.2

tolerations: []