apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-test
  namespace: core-services
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: core-services-redirect-test@kubernetescrd
spec:
  rules:
  - host: "potate.dev.skyloft.cc"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-test
  namespace: core-services
spec:
  redirectRegex:
    regex: "^(.)*"
    replacement: "https://google.com"
    permanent: true