appname: longhorn-restorer
namespace: core-services
project: core-services
label: app
order: 2

chart:
  repo: ghcr.io/dmahmalat/charts
  version: 0.0.2
  name: longhorn-restorer
  namespace: core-services