apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-dns
  namespace: core-services
spec:
  project: default
  source:
    repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    path: dev/acme-dns
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true