apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: core-services
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.3.1
    chart: cert-manager
    helm:
      valueFiles:
      - cert-manager/values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true