fullnameOverride: coredns
k8sAppLabelOverride: kube-dns

replicaCount: 2

hpa:
  minReplicas: 2

service:
  name: kube-dns
  clusterIP: 10.43.0.10

serviceAccount:
  create: true

prometheus:
  service:
    enabled: true

autoscaler:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule