apiVersion: batch/v1
kind: CronJob
metadata:
  name: master-dns-update
  namespace: core-services
  labels:
    chart: {{ include "skyloft.chart" . }}
spec:
  schedule: {{ .Values.dnsUpdate.cron | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          restartPolicy: Never
          containers:
          - name: dns-updater
            image: {{ .Values.dnsUpdate.image }}
            imagePullPolicy: IfNotPresent
            args: [ "-q", "-O", "/dev/null",
              "https://$(DOMAIN_USER):$(DOMAIN_PASS)@domains.google.com/nic/update?hostname=$(DOMAIN_MASTER)" ]
            env:
            - name: DOMAIN_MASTER
              value: {{ .Values.dnsUpdate.domain }}
            - name: DOMAIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dnsUpdate.secret }}
                  key: domainUser
            - name: DOMAIN_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dnsUpdate.secret }}
                  key: domainPass