apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: core-services
spec:
  project: default
  sources:
  - repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    ref: skyloft
  - repoURL: https://traefik.github.io/charts
    targetRevision: v21.2.0
    chart: traefik
    helm:
      valueFiles:
      - $skyloft/dev/core-services/traefik/values.yaml
  - repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    path: dev/core-services/traefik/ingress
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
      prune: true