apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: cockroachdb
  namespace: core-services
  labels:
    chart: {{ include "cockroachdb-resources.chart" . }}
spec:
  entryPoints:
  - db
  routes:
  - match: HostSNI(`*`)
    services:
    - name: cockroachdb
      port: 26257