appname: metrics-server
namespace: core-services
project: core-services
label: app
priority: 1

chart:
  repo: https://kubernetes-sigs.github.io/metrics-server/
  version: v3.8.4
  name: metrics-server
  namespace: kube-system