apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagspaces
spec:
  selector:
    matchLabels:
      run: tagspaces
  replicas: 1
  template:
    metadata:
      labels:
        run: tagspaces
    spec:
      containers:
      - name: tagspaces
        image: exagone313/acme-dns-sidecar
        ports:
        - containerPort: 80