appname: longhorn
namespace: core-services
project: core-services
label: app
priority:
  argocd.argoproj.io/sync-wave: "0"

chart:
  repo: https://charts.longhorn.io
  version: v1.4.1
  name: longhorn
  namespace: core-services