email: d@mahmalat.com
domains:
  - topName: skyloft.cc
    name: dev.skyloft.cc
    eabId: 123456

secrets:
  key: cert-domain-tls-key
  auth: cert-domain-tls-auth

google:
  acmeEabUrl: https://dv.acme-v02.api.pki.goog/directory
  acmeApiUrl: https://acmedns.googleapis.com/v1