appname: cert-manager
namespace: core-services
project: core-services
path: cert-manager
label: ""

chart:
  repo: https://charts.jetstack.io
  version: v1.11.0
  name: cert-manager
  namespace: core-services