appname: cert-manager
namespace: core-services
project: core-services
label: app
priority: 1

chart:
  repo: https://charts.jetstack.io
  version: v1.11.0
  name: cert-manager
  namespace: core-services