---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev.skyloft.cc
spec:
   acme:
    email: dany@mahmalat.com
    server: https://dv.acme-v02.api.pki.goog/directory
    externalAccountBinding:
      keyID: a5427bdfd10d76338eeb6c421137a389
      keySecretRef:
        name: eab-dev.skyloft.cc
        key: secret
    disableAccountKeyGeneration: false
    privateKeySecretRef:
      name: acme-dev.skyloft.cc
    solvers:
    - http01:
        ingress:
          class: traefik

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.skyloft.cc
  namespace: core-services
spec:
  dnsNames:
    #- "*.dev.skyloft.cc"
    - "dev.skyloft.cc"
  secretName: dev.skyloft.cc
  issuerRef:
    name: dev.skyloft.cc
    kind: ClusterIssuer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: core-services
spec:
  tls:
  - secretName: dev.skyloft.cc
  rules:
  - host: argo.dev.skyloft.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80