---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.skyloft.cc
  namespace: core-services
spec:
  dnsNames:
    - dev.skyloft.cc
  secretName: dev.skyloft.cc
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tagspaces
  namespace: core-services
spec:
  tls:
  - secretName: dev.skyloft.cc
  rules:
  - host: dev.skyloft.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tagspaces
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: core-services
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagspaces
  namespace: core-services
spec:
  selector:
    matchLabels:
      run: tagspaces
  replicas: 1
  template:
    metadata:
      labels:
        run: tagspaces
    spec:
      containers:
      - name: tagspaces
        image: dmahmalat/tagspaces
        ports:
        - containerPort: 80