apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-service
  namespace: core-services
  labels:
    chart: {{ include "minio-resources.chart" . }}
spec:
  tls:
  - secretName: {{ .Values.ingress.cert }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000