apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-backup
  namespace: core-services
  labels:
    chart: {{ include "minio-resources.chart" . }}
spec:
  schedule: {{ .Values.backup.cron }}
  successfulJobsHistoryLimit: 24
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.tolerations }}
          tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
          - name: rclone
            image: {{ .Values.image }}
            args: [ "sync", "$(SRC_REMOTE):$(SRC_PATH)", "$(DST_REMOTE):$(DST_PATH)" ]
            envFrom:
            - configMapRef:
                name: minio-backup
            env:
            - name: RCLONE_CONFIG_SRC_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.minio }}
                  key: AWS_ACCESS_KEY_ID
            - name: RCLONE_CONFIG_SRC_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.minio }}
                  key: AWS_SECRET_ACCESS_KEY
            - name: RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.gcs }}
                  key: GCS_ACCESS_KEY

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-backup
  namespace: core-services
  labels:
    chart: {{ include "minio-resources.chart" . }}
data:
  # Source configuration
  SRC_REMOTE: "src"
  SRC_PATH: {{ .Values.backup.src.bucket }}
  RCLONE_CONFIG_SRC_TYPE: "s3"
  RCLONE_CONFIG_SRC_REGION: {{ .Values.backup.src.region }}
  RCLONE_CONFIG_SRC_PROVIDER: "Minio"
  RCLONE_CONFIG_SRC_ENV_AUTH: "false"
  RCLONE_CONFIG_SRC_ENDPOINT: "https://{{ .Values.ingress.host }}"

  # Destination configuration
  DST_REMOTE: "dst"
  DST_PATH: {{ .Values.backup.dst.bucket }}
  RCLONE_CONFIG_DST_TYPE: "google cloud storage"
  RCLONE_GCS_BUCKET_POLICY_ONLY: "true"