appname: errorpages
namespace: core-services
project: core-services
label: app
priority: 1

chart:
  repo: https://dmahmalat.github.io/charts/
  version: v1.0.0
  name: errorpages
  namespace: core-services