{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: core-services
  labels:
    chart: {{ include "longhorn-resources.chart" . }}
spec:
  tls:
  - secretName: {{ .Values.ingress.cert }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
{{- end }}