kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nobackup
  labels:
    chart: {{ include "longhorn-resources.chart" . }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: 3
  staleReplicaTimeout: 30
  fromBackup: ""
  fsType: ext4
  recurringJobSelector: '[{"name":"nobackup", "isGroup":true}]'