apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-errors
  namespace: core-services
spec:
  errors:
    status:
    - "400-599"
    query: /{status}.html
    service:
      name: errorpages
      port: 80