appname: cert-manager-google-domains
namespace: core-services
project: default
label: app
order: 1

chart:
  repo: ghcr.io/dmahmalat/charts
  version: 1.1.3
  name: cert-manager-webhook-google-domains
  namespace: default