appname: cert-manager-google-domains
namespace: core-services
project: core-services
path: cert-manager-google-domains
label: ""

chart:
  repo: https://dmahmalat.github.io/charts/
  version: v1.0.0
  name: cert-manager-webhook-google-domains
  namespace: core-services