appname: cert-manager-google-domains
namespace: core-services
project: core-services
label: app
order: 1

chart:
  repo: oci://ghcr.io
  version: v1.1.2
  name: dmahmalat/charts/cert-manager-webhook-google-domains
  namespace: core-services