apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: longhorn-backup
  namespace: core-services
spec:
  cron: "30 * * * *"
  task: "backup"
  groups:
  - default
  retain: 1
  concurrency: 1