apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm
  namespace: core-services
spec:
  project: core-services
  sources:
  - repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    ref: skyloft
  - repoURL: https://charts.jetstack.io
    targetRevision: v1.11.0
    chart: cert-manager
    helm:
      valueFiles:
      - $skyloft/apps/core-services/cert-manager/values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true