apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-google-domains-helm
  namespace: core-services
spec:
  project: core-services
  sources:
  - repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    ref: skyloft
  - repoURL: https://dmahmalat.github.io/charts/
    targetRevision: v1.0.1
    chart: cert-manager-webhook-google-domains
    helm:
      valueFiles:
      - $skyloft/apps/core-services/cert-manager-google-domains/values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true