apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-helm
  namespace: core-services
spec:
  project: core-services
  sources:
  - repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    ref: skyloft
  - repoURL: https://coredns.github.io/helm
    targetRevision: v1.19.10
    chart: coredns
    helm:
      valueFiles:
      - $skyloft/apps/core-services/coredns/values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true