apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-helm
  namespace: core-services
spec:
  project: core-services
  sources:
  - repoURL: https://github.com/dmahmalat/skyloft.git
    targetRevision: HEAD
    ref: skyloft
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: v3.8.4
    chart: metrics-server
    helm:
      valueFiles:
      - $skyloft/apps/core-services/metrics-server/values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true