deployment:
  replicas: 2

fullnameOverride: traefik

additionalArguments:
  - "--api.insecure=true"
  #- "--entrypoints.web.http.middlewares=core-services-redirect-errors@kubernetescrd"
  #- "--entrypoints.websecure.http.middlewares=core-services-redirect-errors@kubernetescrd"

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule