deployment:
  replicas: 1

fullnameOverride: traefik

logs:
  general:
    level: DEBUG #TEST

ports:
  traefik:
    port: 9000
    exposedPort: 9000
    protocol: TCP
    expose: false
  metrics:
    port: 9100
    exposedPort: 9100
    protocol: TCP
    expose: false
  web:
    middlewares:
      - core-services-redirect-https@kubernetescrd
      - core-services-redirect-errors@kubernetescrd
    port: 8000
    exposedPort: 80
    protocol: TCP
    expose: true
  websecure:
    http3:
      enabled: false
    tls:
      enabled: true
    middlewares:
      - core-services-redirect-errors@kubernetescrd
    port: 8443
    exposedPort: 443
    protocol: TCP
    expose: true
  db:
    port: 26257
    exposedPort: 26257
    protocol: TCP
    expose: true

additionalArguments:
  - "--api.insecure=true"

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesIngress:
    publishedService:
      enabled: true

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule