apiVersion: v1
kind: Service
metadata:
  name: errorpages
  namespace: core-services
spec:
  type: ClusterIP
  selector:
    app: errorpages
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080