appname: cockroachdb
namespace: core-services
project: core-services
label: app
order: 2

chart:
  repo: https://dmahmalat.github.io/charts
  version: v10.0.7
  name: cockroachdb
  namespace: core-services