appname: cockroachdb
namespace: core-services
project: core-services
path: cockroachdb
label: ""

chart:
  repo: https://charts.cockroachdb.com
  version: v10.0.6
  name: cockroachdb
  namespace: core-services