appname: cockroachdb
namespace: core-services
project: core-services
label: app
order: 2

chart:
  repo: https://charts.cockroachdb.com
  version: v10.0.6
  name: cockroachdb
  namespace: core-services