conf:
  single-node: true #TEST
  cluster-name: skyloft

tls:
  enabled: false

storage:
  persistentVolume:
    size: 1Gi

fullnameOverride: cockroachdb

init:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

statefulset:
  replicas: 1 #TEST
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule