apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-404
  namespace: core-services
  labels:
    chart: {{ include "traefik-resources.chart" . }}
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`{host:.+}`)
    priority: 1
    middlewares:
    - name: redirect-404
      namespace: core-services
    services:
    - kind: Service
      name: errorpages
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-404
  namespace: core-services
  labels:
    chart: {{ include "traefik-resources.chart" . }}
spec:
  redirectRegex:
{{- if .Values.notFound.host }}
    regex: ".*"
    replacement: https://{{ .Values.notFound.host }}{{ .Values.notFound.path }}
{{- else }}
    regex: "^(?:https?://)?(?:[^@/]+@)?([^:/]+)"
    replacement: https://$1{{ .Values.notFound.path }}
{{- end }}