apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: core-services
  labels:
    chart: {{ include "traefik-resources.chart" . }}
spec:
  stripPrefixRegex:
    regex:
    - ^/[^/]+