# service:
#   annotations:
#     traefik.ingress.kubernetes.io/service.passhostheader: "true"

extraEnvVars:
  - name: MINIO_SERVER_URL
    value: https://s3.dev.skyloft.cc/
  - name: MINIO_BROWSER_REDIRECT_URL
    value: https://s3.dev.skyloft.cc/dashboard/

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule